### PR TITLE
Use a single sql file to create the mapstore schema and populate it (…

### PR DESCRIPTION
**Pull request by landryb**
…#272)

### CODE REVIEW

**Comment by tdipisa** [comment]
@landryb thank you for this. I've assigned it to a reviewer.

**Review by offtherailz — APPROVED** [review]
Need to update some reference to this file in documentation @catmorales ?

**Comment by catmorales** [comment]
>Need to update some reference to this file in documentation @catmorales ?

yes in the database configuration paragraph, thank you @offtherailz 
and maybe if you have changed the name of the schema "geostore" to "mapstore" update it too

 https://github.com/georchestra/mapstore2-georchestra/blob/master/docs/source/database/index.rst or 
https://docs.georchestra.geo-solutions.it/en/latest/database/index.html

**Comment by offtherailz** [comment]
I updated the documentation in #268 also for this part

**Pull request merged**
