### PR TITLE
Integrate msIframe connector

### PR DESCRIPTION
**Pull request by jusabatier**
Following https://github.com/georchestra/mapstore2-georchestra/issues/476

As explained in our last call, I think this still the better alternative.

The API documentation is available here : https://gitlab.agglo-lepuyenvelay.fr/jusabatier/msiframe/-/blob/master/README.md

This way it's only added to the Georchestra's version as you said me that you don't want maintain it for Mapstore.

I still have some questions : 

- Is the setParams (POST) bugued on master ? 

When I tested, I redirect to it but it always redirect to : `/mapstore/#/viewer/openlayers/config?queryParamsID=###` even if I provide a page parameter.

**Edit : I investigated and found out that it may be due to my environment log level (DEBUG).
In Spring 5.1, 5.2 and probably 5.3 (the MS version), request logs can flush the request content for form-urlencoded content types and so the controller can't get it. (cf. https://github.com/spring-projects/spring-framework/issues/22985)
I will test Monday with WARN logging level and it may correct this bug.**

- Is `/mapstore/#/viewer/openlayers/config` based on the same configs files as `/mapstore/#/` ? (config.json & localConfig.json)

### CODE REVIEW

**Comment by jusabatier** [comment]
Some explanations : 

It add a `/mapstore/msiframe` endpoint.

It's possible to define a default mapstore's context to use via `msIframe.defaultContext` in mapstore.properties,
if none is defined as default or in request params, it redirect to `/mapstore/#/`.

The jsp's javascript algorithm : 

- Check if we use a context or the default config
- Download context file or config.json/localConfig.json
- Retrieve backgrounds and available catalogs from downloaded file
- Analyze request parameters to populate a map, page and action objects
- Post those objects to `/mapstore/rest/config/setParams`

**Comment by jusabatier** [comment]
I tested this morning to use WARN for debug level instead of DEBUG, and everything works fine.

So the bug with logger flushing the request param when they're form-urlencoded is still present in the MS2's spring version.
(cf. https://github.com/spring-projects/spring-framework/issues/22985)

So this connector is fully working.

Any feedbacks @tdipisa @MaelREBOUX @catmorales @landryb ?

Once it will be merged, I wonder were can I push some documentation for it ?
Currently the README.ms refer to https://docs.georchestra.geo-solutions.it/en/latest/, but it doesn't look to be the same as the docs folder of the project.

**Comment by jusabatier** [comment]
@tdipisa Can this PR be merged soon ? 

Curently I have to use a fork and recompile MS to embed it.

**Comment by jusabatier** [comment]
@tdipisa Sorry to ask again, but when this PR can be merged ? 

Do you expect me to do anything for this before merging ?

**Review by tdipisa — COMMENTED** [review]
Hi @jusabatier I'm sorry for the late answer. At a first look the strategy seems ok but unfortunately we don't have enough opportunities at the moment for a proper review/evaluation of the solution and QA testing that is part of all our reviews. Consider anyway that we have also implemented [this](https://github.com/georchestra/mapstore2-georchestra/issues/476#issuecomment-1268070032) as requested. Therefore I'm wondering why you need two different alternatives in place.

**Comment by jusabatier** [comment]
As already explained, IMO this alternative is simpler than the one you implemented because it's closer to sviewer params.

What I understand during our discussions is that I have the responsability to maintain this implementation because it's wil just be an overlay for mapstore2-georchestra and this isn't your code, but both will be included.

Some feedbacks about this @landryb @MaelREBOUX @catmorales ?

**Comment by landryb** [comment]
i'm pretty sure what was agreed by everyone in the last meeting was:
- geosolutions wasnt willing to be responsible for this code, but was ok with merging it. So i dont understand why there's talk about "not having opportunities at the moment for a proper review"...
- both solutions had their pros and cons so it made sense to have both

**Pull request merged**
