### PR TITLE
#36 user session management for contexts

### PR DESCRIPTION
**Pull request by mbarto**
Implementation of user session management.

Some highlights:
 * the loadContextAndMap epic is overridden with a custom loadUserSessionBeforeMapEpic, that loads the session during context/map loading and injects it properly in actual configuration
 * the same happens for loadMapConfigAndConfigureMap, so that session can be loaded also for maps not tied to a context
 * js/epics/usersession.js contains custom epics for saving/updating, loading and removing the user session; they use epics creators from the MapStore framework
 * js/plugins/UserSession.jsx is the plugin that enables usersession into a context (or the default viewer), including reducers and epics, and also the burgermenu item to remove the session

The session actually saved includes:
 * map status (zoom, center, layers and groups)
 * maptemplates favourites
 * userPlugins activation status

The session name is <context_resource_id>.<mapId>.<username>. (mapId is not present for a context default map, while a map without any context is saved as default.<mapId>.<username>

### CODE REVIEW

**Comment by offtherailz** [comment]
https://github.com/geosolutions-it/MapStore2/pull/5036 merged, please proceed

**Comment by mbarto** [comment]
@offtherailz about loading maps that are not context, they are on my radar (I put a list of todos at the end of the description, one of which is "enable sessions also for normal maps", this should cover loading maps that are not context).

About providing this functionality at framework level: I am not convinced managing sessions the way we do for georchestra has to be extended as is to the standard product, this is the reason why I put at the framework level only the basic machinery. This does not mean we cannot try to move it later, partially or completely. My intention is to use the georchestra project as a testbed for this functionality and move it to the framework when it's more consolidated.

I see the contexts/maps loading machinery already as a complex workflow, and I would not make it more complicated until I am not sure about it.

That said, if you have ideas for a better integration, any advice is accepted.

**Comment by mbarto** [comment]
@offtherailz I pushed unit test, some documentation and completed the workflow, I will do more manual testing and eventually remove the WIP

**Comment by mbarto** [comment]
@offtherailz @tdipisa the PR is ready for review

**Comment by tdipisa** [comment]
@offtherailz @mbarto 
according to what we have discussed this afternoon it would be better to:
- Manage the user session client side using the session storage by default
- Provide the possibility for the administrator to enable the user session server side by storing it inside the MS's DB with a configurable interval (probably we should consider a minimum interval value). This will go in addition to the client side session storage one that will be persisted more frequently. The User Session plugin can be configured in the App Context wizard in the same way of other plugins (we will make it enabled by default)
- Manage the user session per application context (regardless the user is using a saved context map or not)

**Comment by mbarto** [comment]
@offtherailz @tdipisa I pushed the latest changes to enable improvements made on mapstore

**Pull request merged**
