### PR TITLE
Use github actions for CI

### PR DESCRIPTION
**Pull request by landryb**
Dunno what @geosolutions-it uses for CI, but @georchestra uses github actions since a month or so (see georchestra/georchestra#2931) - i've been tinkering with github actions on mapstore2-georchestra repo this morning, and finally got to a point where i have it building a war and making it available as an artifact, which allows to download a zip containing mapstore-$SHA.war.

I personally have zero interest in adding the goo for docker images/repo etc, but so far this fits my need (not having to pull/fetch/recompile locally).

@fvanderbiest what do you think about it ? @tdipisa do you have some plans wrt CI ?

### CODE REVIEW

**Comment by fvanderbiest** [comment]
Thanks Landry, this looks good.

Having a docker image build pipe pushing to docker hub would be perfect. I can setup a docker hub repository in https://hub.docker.com/u/georchestra if you guys are OK.

**Comment by tdipisa** [comment]
@landryb I haven't concerns about that, we usually use Jenkins for our CI/CD purposes (we are using it for our geOchestra dev). Therefore, if this is useful for you nd other geOrchestra team members, I have no objections. I only would like to involve our dev and devops teams on this before merging the PR in order to have their feedback too. Thank you.

**Comment by landryb** [comment]
>  I only would like to involve our dev and devops teams on this before merging the PR in order to have their feedback too.

that's exactly why i wanted get feedback from someone in your team, to make sure it wouldn't conflict with some kind of internal process you might have. Since the other georchestra projects are moving from jenkins to gh actions...

**Comment by landryb** [comment]
@offtherailz thanks - @tdipisa should i merge the PR ?

**Comment by tdipisa** [comment]
Thank you so much for this @landryb, PR merged.

**Pull request merged**
