### PR TITLE
#194: migrate externalized config loader to use standard mapstore ser…

### PR DESCRIPTION
**Pull request by mbarto**
…vices

### CODE REVIEW

**Comment by offtherailz** [comment]
Does it need https://github.com/geosolutions-it/MapStore2/pull/4986/ ? to be merged?

**Comment by catmorales** [comment]
Could you please, explain us what will be changed ? 
Because we will need to change our test configuration.

**Comment by mbarto** [comment]
@offtherailz no, that is not needed

**Comment by mbarto** [comment]
@catmorales no changes in installation are needed for this, we have just switched to using standard MapStore backend services instead of a custom servlet made for GeOrchestra

**Pull request merged**
