### PR TITLE
#401: Updated versioning

### PR DESCRIPTION
**Pull request by dsuren1**
## Description
This PR slightly modifies the versioning to be stable when deployed from docker image and also to give complete control on versioning in the application for both the main and the submodule.

**Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines: https://github.com/geosolutions-it/MapStore2/blob/master/CONTRIBUTING.md
- [x] Docs have been added / updated (for bug fixes / features)

**What kind of change does this PR introduce?** (check one with "x", remove the others)
 - [x] Enhancement

## Issue

**What is the current behavior?**
#401 

**What is the new behavior?**
The versioning is always based on the version (stable branch names) provided in `version.txt`

## Breaking change
**Does this PR introduce a breaking change?** (check one with "x", remove the other)
 - [ ] Yes, and I documented them in migration notes
 - [x] No

### CODE REVIEW

**Review by tdipisa — APPROVED** [review]

**Comment by tdipisa** [comment]
@dsuren1 I think you have to backport to 2021.02.xx branch.

**Comment by catmorales** [comment]
@tdipisa ok it seems that  the [docker image](https://hub.docker.com/r/geosolutionsit/mapstore2-georchestra/tags) has not been updated. Do i have to wait a little ?

**Comment by tdipisa** [comment]
@catmorales we have merged few minutes ago. We have to wait the automatic build and deploy.

**Comment by tdipisa** [comment]
Thank you @catmorales

**Pull request merged**
