### PR TITLE
use the same debian package version conventions as in georchestra (#463)

### PR DESCRIPTION
**Pull request by landryb**
reworks what was done in #407, use the branch to determine if we're on master
or not, prepend 99 if that's the case, and use maven timestamp and short git
commit sha.

### CODE REVIEW

**Comment by landryb** [comment]
and fixes #463 ofc.

**Comment by landryb** [comment]
ofc the github action in https://github.com/landryb/mapstore2-georchestra/actions/runs/1746226674 failed because the branch is `fix/debianPackageVersion` ...

**Review by pmauduit — APPROVED** [review]

**Comment by pmauduit** [comment]
> tested:
> 
> * on `master`, produces `georchestra-mapstore_99.master.202201251523~7c61adb-1_all.deb`
> * on `2021.02.xx`, produces `georchestra-mapstore_2021.02.xx.202201251525~a99d420-1_all.deb`

LGTM but have you tested if reprepro is ok with such versioning schemes ?

**Comment by landryb** [comment]
i'll test it but as soon as the `Version` field inside the debian package shows the complete thing (instead of 'just 20.1.3-georchestra' like now) i'm sure reprepro will be happier.

to fix the jobs on PRs/branches, i'll work on a fix for my PR to prefix `99` as soon as the branch name doesnt match `^20\d\d` i think that'd be cleaner.

**Comment by landryb** [comment]
> to fix the jobs on PRs/branches, i'll work on a fix for my PR to prefix 99 as soon as the branch name doesnt match ^20\d\d i think that'd be cleaner.

af30265 just does that.

**Comment by landryb** [comment]
i dunno for reprepro but debian has no issues upgrading a previous package with the one from https://github.com/georchestra/mapstore2-georchestra/actions/runs/1755285225:
```
Unpacking georchestra-mapstore (99.master.202201270900~af30265) over (20.1.3-georchestra) ...
```

**Pull request merged**
