### PR TITLE
Update to MapStore 2021.02.xx

### PR DESCRIPTION
**Pull request by offtherailz**
This PR updates geo-orchestra to MapStore 2021.02.xx. 

Please follow the guidelines to migrate the data-dir. 

Draft, waiting of merge and update of sub-module with this fix:
https://github.com/geosolutions-it/MapStore2/pull/7569

### CODE REVIEW

**Comment by landryb** [comment]
nice, that would allow to revert #427 i think.. @fvanderbiest @tkohr ?

**Comment by offtherailz** [comment]
good point @landryb I added the change to the sub-module in the PR

**Comment by tkohr** [comment]
yes, great news the update, thanks @offtherailz !

**Comment by landryb** [comment]
Fwiw, i see that github actions built fine (cf https://github.com/georchestra/mapstore2-georchestra/actions/runs/1508196635) but locally (debian 11, npm 7.5, nodejs 12.22 from debian) master fails now:
```
$./build.sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: georchestra@1.2.0
npm ERR! Found: eslint@7.8.1
npm ERR! node_modules/eslint
npm ERR!   dev eslint@"7.8.1" from the root project
npm ERR!   peer eslint@">= 7.5.0" from @mapstore/eslint-config-mapstore@1.0.3
npm ERR!   node_modules/@mapstore/eslint-config-mapstore
npm ERR!     dev @mapstore/eslint-config-mapstore@"1.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer eslint@"2.x - 6.x" from eslint-plugin-import@2.20.2
npm ERR! node_modules/eslint-plugin-import
npm ERR!   dev eslint-plugin-import@"2.20.2" from the root project
npm ERR!   peer eslint-plugin-import@">= 2.20.2" from @mapstore/eslint-config-mapstore@1.0.3
npm ERR!   node_modules/@mapstore/eslint-config-mapstore
npm ERR!     dev @mapstore/eslint-config-mapstore@"1.0.3" from the root project
```

i'll retry after removing `node_modules`, just in case others also try to build it. And anyway we're using github actions artifacts for our deployments...

**Comment by landryb** [comment]
after removing `node_modules`, different error, same build failure :)
```
$./build.sh
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: georchestra@1.2.0
npm ERR! Found: react@16.10.1
npm ERR! node_modules/react
npm ERR!   react@"16.10.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^0.14.0 || ^15.0.0" from @geosolutions/react-joyride@1.10.2
npm ERR! node_modules/@geosolutions/react-joyride
npm ERR!   @geosolutions/react-joyride@"1.10.2" from the root project
```

bah, not going to dig into npm madness :) will test the artifact.

**Comment by offtherailz** [comment]
Hi, this is a known issues with npm 7.
https://github.com/geosolutions-it/MapStore2/issues/7181

 Please use npm 6.My version is 6.14.13.

**Comment by Gaetanbrl** [comment]
@landryb  https://github.com/georchestra/mapstore2-georchestra/issues/396

**Comment by landryb** [comment]
then README.md should be amended to state so, currently it says `npm >= 6.` ;)

**Comment by Gaetanbrl** [comment]
> then README.md should be amended to state so, currently it says npm >= 6. ;)

Indeed, but i dunno what is the behaviors with >7.x (maybe works... or not).
So `npm = 6` is maybe the only one.

**Pull request merged**
