### PR TITLE
#585: Print layer with visibility limits applied

### PR DESCRIPTION
**Pull request by dsuren1**
### Description
This PR updates the MS submodule which contains fix for printing layers with visibility limits (scale limit) applied

### Issue
[#8998](https://github.com/geosolutions-it/MapStore2/issues/8998) (MS issue)
- #585

### CODE REVIEW

**Comment by ElenaGallo** [comment]
Hi @dsuren1, 
I create [this map context](https://georchestra.geo-solutions.it/mapstore/#/context/8998/4222) for the test and I  try to print a layer with visibility limits applied but it is not possible.
ssss

**Comment by tdipisa** [comment]
@ElenaGallo you can test now.

**Comment by ElenaGallo** [comment]
@tdipisa test passed on geOrchestra DEV.

**Comment by tdipisa** [comment]
> @tdipisa test passed on geOrchestra DEV.

ok, I'm about to raise a backport PR to 2022.02.xx. Thank you.

**Pull request merged**
