### PR TITLE
Update mapstore.yml

### PR DESCRIPTION
**Pull request by offtherailz**
As for #473, we would like to run build also on PRs, in order to prervent build failures of any case.

I see that anyway docker publishing are allowed only on master or tags of the main repository. So this change should be enough.

Please let me know

### CODE REVIEW

**Comment by landryb** [comment]
that would mean github would build the remote branch upon receiving a PR ?  this is already done when the PR source branch is being pushed to the user's repo, no ?

**Comment by offtherailz** [comment]
This allows the checks you see in this PR here, so we can see if everything went well before the review.
We can even force to not merge if the tests didn't pass from project settings, if we want (admins can anyway merge)

**Review by landryb — APPROVED** [review]
I'm no github actions expert but this seems like an improvement to me :)

**Comment by tdipisa** [comment]
@offtherailz please check for the backport if all ok.

**Pull request merged**
