### PR TITLE
Reorganize readme, infos about NodeJS >14.x

### PR DESCRIPTION
**Pull request by Gaetanbrl**
This PR includes : 

* More info about NodeJS install and specify NodeJS >14.x is not fully compatible (see #396)
* Change titles and create steps to follow

⚠️ Not sur to target master branch... if not, what is correct branch for external PR (workflow) ?

### CODE REVIEW

**Comment by tdipisa** [comment]
@offtherailz can you please review this? Thank you.

**Review by offtherailz — COMMENTED** [review]
:arrow_double_down: :arrow_double_down: :arrow_double_down: 
- [ ] I think you should invert the order of JDK installation and Maven installation.

https://maven.apache.org/install.html

the other information are correct and useful :+1: :+1:

**Comment by Gaetanbrl** [comment]
I will invert JDK and maven (better) ;) 
Thanks

**Comment by Gaetanbrl** [comment]
- [ ]  I think you should invert the order of JDK installation and Maven installation.

Done. Thx.

**Review by offtherailz — APPROVED** [review]

**Pull request merged**
