### PR TITLE
Switch Mapstore2 submodule to georchestra fork

### PR DESCRIPTION
**Pull request by tkohr**
This PR switches the Mapstore2 submodule to a georchestra branch of the georchestra fork of Mapstore2. This allows to integrate recent developments that have been accepted and merged into Mapstore2 until updating the submodules to branch `2021.02.xx` which involves more obstacles.

### CODE REVIEW

**Comment by fvanderbiest** [comment]
> which involves more obstacles.

eg #426

**Comment by fvanderbiest** [comment]
Thanks Tobias !

**Comment by landryb** [comment]
will we switch back to the previous source for the submodule once updated to the newer branch in #422 ? (just making sure we avoid conflicts ..)

**Comment by fvanderbiest** [comment]
Yep, we contributed the patch upstream IIRC

**Pull request merged**
