### PR TITLE
#608 Insert maven compiler version

### PR DESCRIPTION
**Pull request by Gaetanbrl**
> ref #608

This PR will fix the build process if we just follow the README (thanks @pierrejego).

### CODE REVIEW

**Comment by Gaetanbrl** [comment]
Don't know wy build fail in CI and works fine in local space.

**Comment by landryb** [comment]
> Don't know wy build fail in CI and works fine in local space.

maybe because github action installs only java 8 ? cf https://github.com/georchestra/mapstore2-georchestra/blob/master/.github/workflows/mapstore.yml#L18

**Comment by Gaetanbrl** [comment]
Just a questiion, is it possible to set the version in the POM or is it not possible (or just bad - or not recomended to ignore java env) ?

E.g with java 11 :

```
<properties>
    <java.version>11</java.version>
</properties>
```

**Comment by pierrejego** [comment]
I think update CI to Java 11 is better than using java 8 to compile.

Can we propose update CI to java 11 ? Or do the communauty prefers to stay on java 1.8 ?

**Comment by Gaetanbrl** [comment]
Also, Java 8 seems not required / not listed in the README :

image

**Comment by Gaetanbrl** [comment]
> Java 8 seems not required / not listed in the README :

8 == 1.8... arf ^^

**Comment by pmauduit** [comment]
> Or do the communauty prefers to stay on java 1.8 ?

As the other geOrchestra modules have already migrated to Java 11 since 22.0.x releases, i am :+1: for such a move. I think also that we already. Checking on one of our environments, it seems that even if the code is compiled with a compatibility target to java8, we are running it into a Java11 runtime.

**Comment by pierrejego** [comment]
Update gh-action to 11 done

**Comment by pierrejego** [comment]
Perhasp need to be backported to 2022.xx ?

**Pull request merged**
